import { Word } from '@/request/globals';

// 声明一个数组，表示哪些按键需要打字音效
export const specialKeys = [
  'ARROWLEFT',
  'ARROWRIGHT',
  'ARROWUP',
  'ARROWDOWN',
  'UP',
  'DOWN',
  'LEFT',
  'RIGHT',
  'HOME',
  'END',
  'ESCAPE',
  'TAB',
  'ENTER',
  'SPACE',
  ' ',
  'BACKSPACE',
  'A',
  'S',
  'D',
  'F',
  'G',
  'H',
  'J',
  'K',
  'L',
  'Q',
  'W',
  'E',
  'R',
  'T',
  'Y',
  'U',
  'I',
  'O',
  'P',
  'Z',
  'X',
  'C',
  'V',
  'B',
  'N',
  'M'
];

export const INITAIL_WORD = {
  id: '81336',
  languageId: '1',
  categoryId: '7',
  word: 'Keep walking , keep growing',
  transliteration: '',
  usPhonetic: '',
  ukPhonetic: '',
  meaning: '不断前行，不断成长',
  meaningShort: '不断前行，不断成长',
  example: "I'm keep walking, keep growing",
  audioUrl: `https://dict.youdao.com/dictvoice?audio=${encodeURIComponent('Keep walking, keep growing')}&type=1`,
  imageUrl: '',
  createdAt: '2025-08-15T11:57:54.994Z',
  updatedAt: '2025-08-22T08:23:21.063Z',
  deletedAt: ''
} as Word;
