import type { Metadata } from 'next';
import './globals.css';
import { ConfigProvider } from 'antd';
import { GameModeProvider } from '@/contexts/GameModeContext';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className='bg-black overflow-x-hidden'>
        <ConfigProvider
          theme={{
            token: {
              colorPrimary: '#7d26cd',
              colorText: '#fff',
              colorBgContainer: '#141414',
              colorBgElevated: '#141414'
            }
          }}>
          <GameModeProvider>{children}</GameModeProvider>
        </ConfigProvider>
      </body>
    </html>
  );
}
