/// <reference types='./globals.d.ts' />
/* tslint:disable */
/* eslint-disable */
/**
 * Typing API - version 1.0
 *
 * Typing应用的API文档
 *
 * OpenAPI version: 3.0.0
 *
 * Contact:
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
export default {
  'general.UserController_create': ['POST', '/user'],
  'general.UserController_findPaginated': ['GET', '/user/paginated'],
  'general.UserController_findMe': ['GET', '/user/me'],
  'general.UserController_findOne': ['GET', '/user/{id}'],
  'general.UserController_remove': ['DELETE', '/user/{id}'],
  'general.AuthController_register': ['POST', '/auth/register'],
  'general.AuthController_login': ['POST', '/auth/login'],
  'general.AuthController_githubAuth': ['GET', '/auth/github'],
  'general.AuthController_githubCallback': ['GET', '/auth/github/callback'],
  'general.AuthController_qqAuth': ['GET', '/auth/qq'],
  'general.AuthController_qqCallback': ['GET', '/auth/qq/callback'],
  'general.AuthController_getProfile': ['GET', '/auth/profile'],
  'general.AuthController_bindGithub': ['GET', '/auth/bind/github'],
  'general.AuthController_bindGithubManual': [
    'POST',
    '/auth/bind/github/manual'
  ],
  'general.AuthController_unbindGithub': ['POST', '/auth/unbind/github'],
  'general.AuthController_bindQQ': ['GET', '/auth/bind/qq'],
  'general.AuthController_bindQQManual': ['POST', '/auth/bind/qq/manual'],
  'general.AuthController_unbindQQ': ['POST', '/auth/unbind/qq'],
  'general.AuthController_getBindings': ['GET', '/auth/bindings'],
  'general.LanguagesController_create': ['POST', '/languages'],
  'general.LanguagesController_findAll': ['GET', '/languages'],
  'general.LanguagesController_findAllActive': ['GET', '/languages/active'],
  'general.LanguagesController_findAllPaginated': [
    'GET',
    '/languages/paginated'
  ],
  'general.LanguagesController_findByCode': ['GET', '/languages/code/{code}'],
  'general.LanguagesController_findOne': ['GET', '/languages/{id}'],
  'general.LanguagesController_remove': ['DELETE', '/languages/{id}'],
  'general.CorpusCategoriesController_create': ['POST', '/corpus-categories'],
  'general.CorpusCategoriesController_findAll': ['GET', '/corpus-categories'],
  'general.CorpusCategoriesController_findAllPaginated': [
    'GET',
    '/corpus-categories/paginated'
  ],
  'general.CorpusCategoriesController_findByLanguageId': [
    'GET',
    '/corpus-categories/language/{languageId}'
  ],
  'general.CorpusCategoriesController_findByDifficulty': [
    'GET',
    '/corpus-categories/difficulty/{difficulty}'
  ],
  'general.CorpusCategoriesController_findByLanguageAndDifficulty': [
    'GET',
    '/corpus-categories/language/{languageId}/difficulty/{difficulty}'
  ],
  'general.CorpusCategoriesController_getDifficultyStats': [
    'GET',
    '/corpus-categories/stats/difficulty'
  ],
  'general.CorpusCategoriesController_getLanguageStats': [
    'GET',
    '/corpus-categories/stats/language'
  ],
  'general.CorpusCategoriesController_findOne': [
    'GET',
    '/corpus-categories/{id}'
  ],
  'general.CorpusCategoriesController_remove': [
    'DELETE',
    '/corpus-categories/{id}'
  ],
  'general.WordsController_create': ['POST', '/words'],
  'general.WordsController_findAllPaginated': ['GET', '/words/paginated'],
  'general.WordsController_findByLanguageId': [
    'GET',
    '/words/language/{languageId}'
  ],
  'general.WordsController_findByCategoryId': [
    'GET',
    '/words/category/{categoryId}'
  ],
  'general.WordsController_findByLanguageAndCategory': [
    'GET',
    '/words/language/{languageId}/category/{categoryId}'
  ],
  'general.WordsController_searchWords': ['GET', '/words/search'],
  'general.WordsController_searchWordsPaginated': [
    'GET',
    '/words/search/paginated'
  ],
  'general.WordsController_getRandomWords': ['GET', '/words/random'],
  'general.WordsController_getLanguageStats': ['GET', '/words/stats/language'],
  'general.WordsController_getCategoryStats': ['GET', '/words/stats/category'],
  'general.WordsController_findOne': ['GET', '/words/{id}'],
  'general.WordsController_remove': ['DELETE', '/words/{id}'],
  'general.SentencesController_create': ['POST', '/sentences'],
  'general.SentencesController_findAllPaginated': [
    'GET',
    '/sentences/paginated'
  ],
  'general.SentencesController_findByLanguageId': [
    'GET',
    '/sentences/language/{languageId}'
  ],
  'general.SentencesController_findByCategoryId': [
    'GET',
    '/sentences/category/{categoryId}'
  ],
  'general.SentencesController_findByLanguageAndCategory': [
    'GET',
    '/sentences/language/{languageId}/category/{categoryId}'
  ],
  'general.SentencesController_searchSentences': ['GET', '/sentences/search'],
  'general.SentencesController_searchSentencesPaginated': [
    'GET',
    '/sentences/search/paginated'
  ],
  'general.SentencesController_getRandomSentences': [
    'GET',
    '/sentences/random'
  ],
  'general.SentencesController_getLanguageStats': [
    'GET',
    '/sentences/stats/language'
  ],
  'general.SentencesController_getCategoryStats': [
    'GET',
    '/sentences/stats/category'
  ],
  'general.SentencesController_findOne': ['GET', '/sentences/{id}'],
  'general.SentencesController_remove': ['DELETE', '/sentences/{id}'],
  'Speech.SpeechController_getYoudaoAudio': ['GET', '/speech/audio']
};
